local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("GameGuy's Script Hub", "Ocean")
local UniversalTab = Window:NewTab("Scripts")
local UniversalSection1 = UniversalTab:NewSection("General")
local UniversalSection2 = UniversalTab:NewSection("Funky Friday")
local UniversalSection3 = UniversalTab:NewSection("Pet Simulator X")
local UniversalTab = Window:NewTab("Settings")
local UniversalSection4 = UniversalTab:NewSection("Settings")
local UniversalSection5 = UniversalTab:NewSection("Credits : Efe Tahça")
UniversalSection1:NewButton("Saza Hub", "Executes Saza Hub", function()
    loadstring(game:HttpGet"https://rawscripts.net/raw/SAZA-HUB_496")()
end)
UniversalSection1:NewButton("V.G Hub", "Executes V.G Hub", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/1201for/V.G-Hub/main/V.Ghub"))()
end)
UniversalSection1:NewButton("Shiny Tool", "Executes ShinyTool", function() --Creates a button
    loadstring(game:HttpGet("https://raw.githubusercontent.com/XLinestX/ShinyToolV2/main/Loader.lua"))()
end)
UniversalSection3:NewButton("BK Hack", " Executes BK Hack", function() --Creates a button
    loadstring(game:HttpGet("https://raw.githubusercontent.com/BLACKGAMER1221/Pet-Simulator-X/main/BK%20Pet.lua"))()
end)
UniversalSection1:NewButton("Soggyware", "Executes Soggyware", function() --Creates a button
    loadstring(game:HttpGet("https://raw.githubusercontent.com/SunkenMuch/Soggyware/main/Main"))()
end)
UniversalSection2:NewButton("Funky Friday Autoplayer", "Funky Friday Script", function() --Creates a button
    loadstring(game:HttpGet("https://raw.githubusercontent.com/wally-rblx/funky-friday-autoplay/main/main.lua"))()
end)
UniversalSection1:NewButton("Supported Games", "Shows Supported Games.", function() --Creates a button
    loadstring(game:HttpGet("https://raw.githubusercontent.com/GameGuyOnYT/GameGuyScriptHub/main/supportedgames.lua"))() 
end)
UniversalSection4:NewKeybind("Hide (Default P)", "Hide", Enum.KeyCode.P, function()
	Library:ToggleUI()
end)
