local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("GameGuy's Script Hub", "Ocean")
local UniversalTab = Window:NewTab("Scripts")
local UniversalSection1 = UniversalTab:NewSection("General")
local UniversalSection2 = UniversalTab:NewSection("Funky Friday")
local UniversalSection3 = UniversalTab:NewSection("Pet Simulator X")
local UniversalSection4 = UniversalTab:NewSection("Clicker Simulator")
local UniversalSection5 = UniversalTab:NewSection("Clicker Simulator")
local UniversalTab = Window:NewTab("Settings")
local UniversalSection6 = UniversalTab:NewSection("Settings")
local UniversalSection7 = UniversalTab:NewSection("Credits : Efe Tahça")
UniversalSection1:NewButton("Saza Hub", "Executes Saza Hub", function()
    loadstring(game:HttpGet"https://rawscripts.net/raw/SAZA-HUB_496")()
end)
UniversalSection1:NewButton("V.G Hub", "Executes V.G Hub", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/1201for/V.G-Hub/main/V.Ghub"))()
end)
UniversalSection1:NewButton("Shiny Tool", "Executes ShinyTool", function() --Creates a button
    loadstring(game:HttpGet("https://raw.githubusercontent.com/XLinestX/ShinyToolV2/main/Loader.lua"))()
end)
UniversalSection3:NewButton("BK Hack", " Executes BK Hack", function() --Creates a button
    loadstring(game:HttpGet("https://raw.githubusercontent.com/BLACKGAMER1221/Pet-Simulator-X/main/BK%20Pet.lua"))()
end)
UniversalSection1:NewButton("Soggyware", "Executes Soggyware", function() --Creates a button
    loadstring(game:HttpGet("https://raw.githubusercontent.com/SunkenMuch/Soggyware/main/Main"))()
end)
UniversalSection2:NewButton("Funky Friday Autoplayer", "Funky Friday Script", function() --Creates a button
    loadstring(game:HttpGet("https://raw.githubusercontent.com/wally-rblx/funky-friday-autoplay/main/main.lua"))()
end)
UniversalSection4:NewButton("LaDamage", "Clicker Simulator Script", function() --Creates a button
    loadstring(game:HttpGet("https://raw.githubusercontent.com/LaDamage/releases/main/Clicker-Simulator.lua"))()
end)
UniversalSection5:NewButton("Universal", "A script that works in all games with general functions.", function() --Creates a button
    loadstring(game:HttpGet("https://paste.ee/r/6rXoq/0",true))()
end)
UniversalSection1:NewButton("Supported Games (Click F9 after clicking this)", "Shows Supported Games.", function() --Creates a button
    print("Normal Scripts : Funky Friday, Pet Simulator X | V.G Hub : https://raw.githubusercontent.com/1201for/Funs-and-Features/main/Features-and-games | Saza Hub : Blox Fruits, Pet Simulator X, Anime Clicker Simulator, Build A Boat, King Legacy, Two Piece | Shiny Tool : Pet Simulator X, Clicker Simulator, Magnet Simulator 2, Pet Legacy, Donate Me Pls, Arsenal | Soggyware : Anime Dimensions, Rebirth Champions X, Tapper Simulator, Anime Clicker Simulator, Anime Tappers, Slap Battles, Farm Life, Clicking Simulator, Burn Everything Simulator, A One Piece Game, Collect All Pets, Untitled Tag Game, Boom Simulator, Pet Simulator X, Chicken Life, Smashing Simulator X, Slashing Simulator, Timber, Big Man Simulator, Tapping Legends X, Pet Legacy")
end)
UniversalSection6:NewKeybind("Hide (Default P)", "Hide", Enum.KeyCode.P, function()
	Library:ToggleUI()
end)
